export const NEWS = {
    FETCH_NEWS_IDS_SUCCES: "[NEWS]FETCH_NEWS_IDS_SUCCES",
    FETCH_NEWS_IDS_FAIL: "[NEWS]FETCH_NEWS_IDS_FAIL",
    FETCH_NEWS_IDS: "[NEWS]FETCH_NEWS_IDS",
    FETCH_ARTICLE: "[NEWS]FETCH_ARTICLE",
    FETCH_ARTICLE_SUCCES: "[NEWS]FETCH_ARTICLE_SUCCES",
    FETCH_ARTICLE_FAIL: "[NEWS]FETCH_ARTICLE_FAIL",
    SHOW_MORE_NEWS: "[NEWS]SHOW_MORE_NEWS"
}

export const ARTICLE = {
    FETCH_ARTICLE: "[ARTICLE]FETCH_ARTICLE",
    FETCH_ARTICLE_SUCCESS: "[ARTICLE]FETCH_ARTICLE_SUCCESS",
    FETCH_ARTICLE_FAIL: "[ARTICLE]FETCH_ARTICLE_FAIL",
    FETCH_COMMENT: "[ARTICLE]FETCH_COMMENT",
    FETCH_COMMENT_SUCCESS: "[ARTICLE]FETCH_COMMENT_SUCCESS",
    FETCH_COMMENT_FAIL: "[ARTICLE]FETCH_COMMENT_FAIL",
    OPEN_CHILDREN: "[ARTICLE]OPEN_CHILDREN",
    CLEAR_STATE: "[ARTICLE]CLEAR_STATAE"
}